SMPL_MUJOCO_NAMES = [
    'Pelvis', 
    'L_Hip', 
    'L_Knee', 
    'L_Ankle', 
    'L_Toe', 
    'R_Hip', 
    'R_Knee', 
    'R_Ankle', 
    'R_Toe', 
    'Torso', 
    'Spine', 
    'Chest', 
    'Neck', 
    'Head', 
    'L_Thorax', 
    'L_Shoulder', 
    'L_Elbow', 
    'L_Wrist', 
    'L_Hand', 
    'R_Thorax', 
    'R_Shoulder', 
    'R_Elbow', 
    'R_Wrist', 
    'R_Hand']

SMPL_ISAAC_NAMES = [
    'Pelvis',
    'L_Hip', 'L_Knee', 'L_Ankle',
    'R_Hip', 'R_Knee', 'R_Ankle',
    'Torso', 'Spine', 'Chest', 'Neck',
    'L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist',
    'R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist',
]

SMPL_BONE_ORDER_NAMES = [
    "Pelvis",
    "L_Hip",
    "R_Hip",
    "Torso",
    "L_Knee",
    "R_Knee",
    "Spine",
    "L_Ankle",
    "R_Ankle",
    "Chest",
    "L_Toe",
    "R_Toe",
    "Neck",
    "L_Thorax",
    "R_Thorax",
    "Head",
    "L_Shoulder",
    "R_Shoulder",
    "L_Elbow",
    "R_Elbow",
    "L_Wrist",
    "R_Wrist",
    "L_Hand",
    "R_Hand",
]

SMPLX_BONE_ORDER_NAMES = [
    'pelvis',
    'left_hip',
    'right_hip',
    'spine1',
    'left_knee',
    'right_knee',
    'spine2',
    'left_ankle',
    'right_ankle',
    'spine3',
    'left_foot',
    'right_foot',
    'neck',
    'left_collar',
    'right_collar',
    'head',
    'left_shoulder',
    'right_shoulder',
    'left_elbow',
    'right_elbow',
    'left_wrist',
    'right_wrist',
    'jaw',
    'left_eye',
    'right_eye',
    'left_index1',
    'left_index2',
    'left_index3',
    'left_middle1',
    'left_middle2',
    'left_middle3',
    'left_pinky1',
    'left_pinky2',
    'left_pinky3',
    'left_ring1',
    'left_ring2',
    'left_ring3',
    'left_thumb1',
    'left_thumb2',
    'left_thumb3',
    'right_index1',
    'right_index2',
    'right_index3',
    'right_middle1',
    'right_middle2',
    'right_middle3',
    'right_pinky1',
    'right_pinky2',
    'right_pinky3',
    'right_ring1',
    'right_ring2',
    'right_ring3',
    'right_thumb1',
    'right_thumb2',
    'right_thumb3'
]